### ISSUE TITLE
Could not pass event PortalCreateEvent

### ISSUE THREAD

**Issue by blackshot** [isokissa3/WorldGuardExtraFlagsPlugin#100]
in my spawn region i have a nether portal and ocassionally i got this error

`ERROR Could not pass event PortalCreateEvent to WorldGuardExtraFlags v4.1.2
18.01 02:39:13 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.event.world.PortalCreateEvent.getBlocks()Ljava/util/ArrayList;
18.01 02:39:13 [Server] INFO at net.goldtreeservers.worldguardextraflags.listeners.EntityListener.onPortalCreateEvent(EntityListener.java:24) ~[?:?]
18.01 02:39:13 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor761.execute(Unknown Source) ~[?:?]
18.01 02:39:13 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at net.minecraft.server.v1_15_R1.EntityPlayer.a(EntityPlayer.java:895) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at net.minecraft.server.v1_15_R1.BlockEnderPortal.a(BlockEnderPortal.java:34) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at net.minecraft.server.v1_15_R1.IBlockData.a(IBlockData.java:214) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at net.minecraft.server.v1_15_R1.Entity.checkBlockCollisions(Entity.java:949) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at net.minecraft.server.v1_15_R1.Entity.move(Entity.java:664) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.e(EntityLiving.java:2255) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at net.minecraft.server.v1_15_R1.EntityHuman.e(EntityHuman.java:1558) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.movementTick(EntityLiving.java:2620) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at net.minecraft.server.v1_15_R1.EntityHuman.movementTick(EntityHuman.java:428) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2381) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at net.minecraft.server.v1_15_R1.EntityHuman.tick(EntityHuman.java:165) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at net.minecraft.server.v1_15_R1.EntityPlayer.playerTick(EntityPlayer.java:426) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.tick(PlayerConnection.java:149) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:260) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1263) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-50]
18.01 02:39:13 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]`

**Comment by isokissa3** [comment]
Was fixed in 78add0a9
