### ISSUE TITLE
Failed to parse flag 'glide' with value 'FORCE'

### ISSUE THREAD

**Issue by NightFuryStrike** [isokissa3/WorldGuardExtraFlagsPlugin#105]
**Paper Version:** git-Paper-93 (MC: 1.15.2)
**WG Version:** 7.0.2-SNAPSHOT;bf2593e (Bukkit Official)
**WG Extra Flags Version:** 4.1.3

**Description of issue**
I have a region above my spawn where I want to force gliding. This worked fine in version 4.1.2 but it seems that now when I used the "force" value, it works until worldguard is reloaded or the server is rebooted.

Console shows the following upon reload:
```
08.02 15:13:33 [Server] WARN [WorldGuard] Failed to parse flag 'glide' with value 'FORCE'
08.02 15:13:33 [Server] WARN [WorldGuard] Failed to parse flag 'glide' with value 'DENY'
08.02 15:13:33 [Server] WARN [WorldGuard] Failed to parse flag 'glide' with value 'DENY'
08.02 15:13:39 [Server] INFO DragonEye issued server command: /region flag spawnglide glide force
```

**Comment by isokissa3** [comment]
Was fixed in 7ceace5
