### ISSUE TITLE
keep-inventory flag duplicating inventories upon death- what is causing it?

### ISSUE THREAD

**Issue by alexrnc** [isokissa3/WorldGuardExtraFlagsPlugin#108]
Hey, I can provide any information required, but I've been spending ages trying to get to the bottom of this issue. I've set up keep inventory in one region of my world using the keep-inventory flag, but upon death, the player keeps the items in their inventory and also drops a copy. This stops happening if I set the keepinventory gamerule to true, which then effects keep inventory across the whole server. There are no errors/issues in the console and I cannot see any plugins that would clash with it. Are there any known plugins that could clash that I've overlooked/other issues that could be causing it?

**Comment by isokissa3** [comment]
This is some other plugin being terrible and not respecting my plugins decision. SlimeFun had some issues but I think it was fixed. I'm not aware of any other plugins doing so. You need to remove your other plugins and add them back to figure out which one is not behaving correctly

**Comment by alexrnc** [comment]
^^ InvRestore plugin doesn't work with keep inventory flag and causes duplication.
