### ISSUE TITLE
Glide Bug fix not fixed

### ISSUE THREAD

**Issue by Sinnethh** [isokissa3/WorldGuardExtraFlagsPlugin#113]
I had compiled the most recent source on the git to get the Glide bug fix but sadly it doesnt work. Can I please get a fixed jar that actually works please

**Comment by isokissa3** [comment]
Could you elaborate? Dev builds automatically build the git version too so theres no reason to compile the project yourself

**Comment by LogGits** [comment]
For me the glide flag gets removed from the region randomly.
WGEF ver 4.1.3
worldguard 7.0.3-SNAPSHOT;2020-2169aa2

**Comment by isokissa3** [comment]
@LogGits Thats because it was fixed in 7ceace5 and the Spigot version does not have the fix, but dev build covers this

**Comment by Sinnethh** [comment]
> @LogGits Thats because it was fixed in [7ceace5](https://github.com/isokissa3/WorldGuardExtraFlagsPlugin/commit/7ceace5eba71a5a0597b4797c7a0e3364b96251e) and the Spigot version does not have the fix, but dev build covers this

I got someone to build the dev build for me and it still didnt work, could you possibly send me the fixed version you have since I can't seem to get it to work

**Comment by isokissa3** [comment]
You can just use the prebuild version from here https://jenkins.isokissa3.fi/
