### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by ThatOneTree** [isokissa3/WorldGuardExtraFlagsPlugin#117]
WEF version: 4.1.4
Tuinity-62  | 1.15.2 

https://pastebin.com/9DcjyBvA

**Comment by isokissa3** [comment]
Not the plugins fault, your server is freezing

**Comment by ThatOneTree** [comment]
It seems like there is barely any tolerance for the server freezing for WEF and immediately bricks it when that error pops up.

**Comment by isokissa3** [comment]
Something is blocking the main thread for whatever reason when sending packets. This could be some patch in Tuinity that is breaking stuff because this hasn't been reported before
