### ISSUE TITLE
give effects for time

### ISSUE THREAD

**Issue by mrcoffee1026** [isokissa3/WorldGuardExtraFlagsPlugin#118]
There doesn't seem to be a way to specify a length of time for the give-effects flag.  One seems to be automatically applied and is stored that way in the configuration for that region... but there's no way of altering this information that I can tell since the command will only accept a number for the second argument and won't accept a third.  I would like to have an effect linger for some length of time after leaving the region if that would be possible... think like... maybe glowing x1 possibly something like regen... and have it linger for a few minutes after leaving the region....  so maybe a player could take advantage of respawning in a particular location in some sort of an arena set up.  (+jump 3x, +speed 5x... think mario power star from the original 8bit nes, for example).  Anyway, it doesn't seem possible to alter the time for the applied effect for now but they cease immediately when you leave the region regardless of what their personal timer is showing when they leave.  Maybe if there was some other option that could be applied to ensure the personal timer was actually paid attention to on departure as well as some magical method for altering the time setting itself.

flags: give-effects [JUMP:(319t-x75)]

command for setting this is
rg flag trampoline give-effects jump 75
whereas it would be cool if it were something like
rg flag trampoline give effects jump 75 1m true
(true for lingering... defaults to how it was before.. which is some magical "319t" setting which is not editable and just lasts forever while and only while inside the region)

**Comment by isokissa3** [comment]
The effect time is unmodifiable to avoid glitches where the player somehow could keep their potion effect and prevent any lasting "damage" to the server. I'm not letting people to edit this even the easy way so I don't get yelled at when some plugin is misbehaving.

If you wan't to give potion effects that last after you leave the region there is simple solution, use the console-command-on-exit flag.

**Comment by mrcoffee1026** [comment]
ah yeh i hadn't even thought of that but that would work, thanks very much!
