### ISSUE TITLE
Add command-RegionHasPlayers and command-RegionNoPlayers flags

### ISSUE THREAD

**Issue by male-gal** [isokissa3/WorldGuardExtraFlagsPlugin#119]
Hi !
A bit of context : I'm looking to reduce amount of commandblocks on my server to improve TPS. I'm actually using a lot of 1.13 "testfor" like commandblocks to detect wether there's player or not in certain areas.

I think it would be nice to have flags triggering when there's some players entering the region (and there was not before) and when some players are leaving the region (and no one's left inside). 

This would be really close to command-on-entry & command-on-exit flags, except it triggers only when the region passes from having no players to having some, and from having some players to not having any.

**Comment by isokissa3** [comment]
You could instead take advantage of the existing flags and maybe use scoreboards to keep track of that yourself.
