### ISSUE TITLE
Add a flag to prevent wooden trapdoors open only

### ISSUE THREAD

**Issue by AerWyn81** [isokissa3/WorldGuardExtraFlagsPlugin#120]
Hello, I would like to know if it was possible to implement a flag that would only prevent the use of wooden trapdoors.

Explanation: On our spawn, we let the flags use, interact for some actions, however players have fun opening all the trapdoors of the lamp posts. If this could be possible, it would be really interesting.

**Comment by isokissa3** [comment]
Dupe of #55
