### ISSUE TITLE
Farm harvesting

### ISSUE THREAD

**Issue by mihiblu** [isokissa3/WorldGuardExtraFlagsPlugin#121]
Hi. 
How can I afford to harvest the farm? I don't know what to put on the allow-block-break.

**Comment by isokissa3** [comment]
Depends on which version of MC u on, SEEDS or WHEAT_SEEDS

**Comment by mihiblu** [comment]
![ScreenShot_20200510214141](https://user-images.githubusercontent.com/35107509/81507589-12f01700-9307-11ea-9968-0336775c934d.png)

**Comment by isokissa3** [comment]
Well then its some other id, use the link provided

**Comment by mihiblu** [comment]
I can't find and run

**Comment by isokissa3** [comment]
Then you are doing something wrong, other people have got it working

**Comment by mihiblu** [comment]
Couldn't you tell me your id for wheat, carrots and potatoes?
