### ISSUE TITLE
Issue With Commands on Entry and on Exit.

### ISSUE THREAD

**Issue by BetaDv** [isokissa3/WorldGuardExtraFlagsPlugin#125]
**Hello guys, i have an issue. I wanted to make a System when you leave a Region you must not have an item.
But, i made it to execute commands, but, once again, it doesn't execute them.
![image](https://user-images.githubusercontent.com/62099784/82654627-b277a880-9c29-11ea-9d1c-f4c7619c86a5.png)
Please help.
![image](https://user-images.githubusercontent.com/62099784/82654677-c6bba580-9c29-11ea-940f-ce0d32dc5447.png)
![image](https://user-images.githubusercontent.com/62099784/82654728-d935df00-9c29-11ea-8d40-c735180253a9.png)
![image](https://user-images.githubusercontent.com/62099784/82654808-f36fbd00-9c29-11ea-8eca-d48b783b3f9c.png)
![image](https://user-images.githubusercontent.com/62099784/82654889-0aaeaa80-9c2a-11ea-8771-f295ca821f7f.png)
![image](https://user-images.githubusercontent.com/62099784/82654958-244ff200-9c2a-11ea-8e69-5d81c5e8e5a5.png)**

**Comment by isokissa3** [comment]
Read the FAQ

**Comment by BetaDv** [comment]
@isokissa3, hello Sir, i've done all of that, but it doesn't work. I tried deoping myself too. But no good result.

**Comment by isokissa3** [comment]
Then you most likely have wrong WG version, check the FAQ

**Comment by BetaDv** [comment]
@isokissa3, i did check that and i have a supported version.

**Comment by isokissa3** [comment]
Then you are doing something wrong, not the plugins fault

**Comment by BetaDv** [comment]
Do you use Discord? So we can talk there maybe? Maybe you could help me.

**Comment by BetaDv** [comment]
I really don't know what i could be doing wrong.

**Comment by isokissa3** [comment]
The plugin page has invitation link

**Comment by BetaDv** [comment]
Thank you!
