### ISSUE TITLE
Clarification on "item-durability"

### ISSUE THREAD

**Issue by s1h4d0w** [isokissa3/WorldGuardExtraFlagsPlugin#126]
I've recently started setting up a PVP arena on my 1.14.4 server, after using this plugin to make that possible on my old 1.12.2 server. However I can't find much information on how exactly I need to set up the "item-durability" flag. 

The SpigotMC page says "Is item durability prevented inside the region". The flag can be set to "none", "yes" and "no", so with the explanation I would assume I need to set it to "yes" to prevent damage to items. 

However I got a lot of reports on 1.12.2 that it wasn't working, so when I was setting it all up again I started wondering if I might have misunderstood and need to set it to "none" or "no". Both kind of make sense too, as it could mean "no/none loss of item durability".

**Comment by isokissa3** [comment]
The description was bad actually and I have fixed that now. The flag acts as is item durability allowed so yes would mean items break and no would mean they don’t take damage.
