### ISSUE TITLE
Blocked cmds not working in region

### ISSUE THREAD

**Issue by regret** [isokissa3/WorldGuardExtraFlagsPlugin#127]
Trying to disable commands in a parkour region so players can't /sethome, etc. 
[screenshot](https://venusaur.org/i/fye76.png)
It doesn't seem to be working. There are two regions, but the parkour region has priority over the spawn region. 
Players are still able to execute these commands even though they are blocked

**Comment by isokissa3** [comment]
Well this is WG flag and not WGEF one so..
