### ISSUE TITLE
Teleport On Entry not Teleporting Certain Ranks

### ISSUE THREAD

**Issue by GTApsycho** [isokissa3/WorldGuardExtraFlagsPlugin#13]
It seems that Teleport on Entry doesn't teleport users with * permissions

**Comment by EvilOlaf** [comment]
Of course it does not as * includes WorldGuard bypass permission nodes to ignore any set flags on region.

**Comment by GTApsycho** [comment]
And what nodes would I need to disable to fix that?

**Comment by EvilOlaf** [comment]
My guess would be `worldguard.region.bypass.<world>`

**Comment by GTApsycho** [comment]
I tried that, but nothing
