### ISSUE TITLE
give-effects-flag doesnt work

### ISSUE THREAD

**Issue by TheoRetisch1** [isokissa3/WorldGuardExtraFlagsPlugin#14]
The give-effect flag doesnt work. It is possible to set the flag but one doesnt get any effects entering the region, there are no errors in the log. The issue exist since you reworked the restore-system. Everything works fine with WorldguardExtraFlagsVersion 2.12.1 but I am looking foward to use the join-location flag.

WorldguardExtraFlags: 2.14.2
Worldguard: 6.2.1;84bc322
PaperSpigiot: MC 1.12.1 #1191

**Comment by mrcoffee1026** [comment]
i didn't notice this ticket when i made mine.  If your user is opped or has a node like worldguard.region.bypass.* set to true for themselves, they will bypass all effects by the give-effect flag.  Deopping myself and setting that node to false for me allowed me to experience all effects by the give-effects flag.  Let me know if that works for you.

**Comment by isokissa3** [comment]
Having permissions to `worldguard.region.bypass.<world>` will prevent the flags from happening, also make sure you have `use-player-move-event` set to true in WorldGuard config
