### ISSUE TITLE
Teleport-On-Entry not working in latest version

### ISSUE THREAD

**Issue by PetKCH** [isokissa3/WorldGuardExtraFlagsPlugin#15]
Hello, the latest version does not execute Teleport-On-Entry, I am on 1.8.8, I downgraded to older version of WGEF and there it works so its not error made by me.

There is nothing printed in console.

**Comment by isokissa3** [comment]
Having permissions to `worldguard.region.bypass.<world>` will prevent the flags from happening, also make sure you have `use-player-move-event` set to true in WorldGuard config
