### ISSUE TITLE
Flags Not Working

### ISSUE THREAD

**Issue by MatticusTheWhite** [isokissa3/WorldGuardExtraFlagsPlugin#16]
Whenever I use one of the special fags the command executes and the region lists the flag in its flag list but the flag doesn't work.  I tried it with multiple flags and every combination of game mode/permission set.  The main flag I would like to work is give-effects but nothing happens.  I've looked over all the config and found nothing that would help.  I also made sure that my WorldGuard and WorldGuardExtraFlags plugins were up to date.  Normal flags work just fine.  If there is any way that I could fix this that would be awesome.  

Thanks,

Matt

**Comment by EvilOlaf** [comment]
Check if `WorldGuardExtraFlagsPlugin`is loaded properly on startup. If unsure paste a full startup log to hastebin or pastebin.
If you have `WorldGuard` bypass permission nodes flags will NOT apply. This includes `wg.*`, `*`, and `OP`-Status.
Check if the region with applied has the highest priority if multiple region are in the same area.

Insufficient information. Server software and version? `WorldGuard` version? `WorldGuardExtraFlagsPlugin` version? Any other plugin that interact with `WorldGuard`? 
"Latest" is NOT a valid answer.

**Comment by MatticusTheWhite** [comment]
I did make sure to test it when out of op mode and it still didn't work. I'm running my server on craftbukkit version 1.12.1 and I'm not sure on the server software I'm running.  I'm running world guard version 6.2.1:84bc322 and world guard extra flags version 2.14.2.  I don't believe there is a plugin interference.

There seems to be an error when loading the plugin into the server.  I'll post a link for the pastebin below.

https://pastebin.com/HNy0SibH

Thanks,

Matt

**Comment by EvilOlaf** [comment]
Worldedit is outdated. Try using 6.x instead of 5.x

**Comment by MatticusTheWhite** [comment]
I got it working! Thank you so much!
