### ISSUE TITLE
give-effects group parameter

### ISSUE THREAD

**Issue by Nicklander** [isokissa3/WorldGuardExtraFlagsPlugin#18]
Please add support for group parameters !
For instance: /region flag test give-effects -g members
Also please make this new version compatible on Minecraft 1.11.2
Thanks alot !

WG Extra Flags: version 2.12.1
Minecraft version: git-Spigot-b32c8f8-4d3bf20 1.11.2-R0.1-Snapshot

**Comment by isokissa3** [comment]
Group parameters are already supported, having multiple group parameters comes down to WG not spuporting it
