### ISSUE TITLE
2.14.2

### ISSUE THREAD

**Issue by madtomic** [isokissa3/WorldGuardExtraFlagsPlugin#20]
command-on-entry & command-on-exit
console-command-on-entry & console-command-on-exit 

These are still not working.

**Comment by EvilOlaf** [comment]
Working nicely for me. Did you make sure that you do not have WorldGuard bypass permission node? Then none of your flags would apply.

**Comment by Pugabyte** [comment]
Duplicate of #19

**Comment by madtomic** [comment]
worldguard.region.bypass.<world> (gives users with this permission the ability to bypass region protection)

Wouldn't this defeated the purpose to have any kind of protections at all in the first place?

IMO: this change is bad as now I need to give all users the ability to bypass region protections.

**Comment by madtomic** [comment]
@EvilOlaf 

I don't have the bypass permission node. Just the normal add greeting and it usually shows up but in new WG. no luck

**Comment by madtomic** [comment]
@EvilOlaf What version of WG/WE are you using to get this plugin to work?

**Comment by EvilOlaf** [comment]
`WorldGuard 6.1.3-SNAPSHOT;c904242` combined with `WorldGuardExtraFlags version 2.14.3` working decent on `Spigot 1.8.8`

**Comment by isokissa3** [comment]
Having permissions to `worldguard.region.bypass.<world>` will prevent the flags from happening, also make sure you have `use-player-move-event` set to true in WorldGuard config
