### ISSUE TITLE
Only SOME Flags are working!

### ISSUE THREAD

**Issue by TheRealExus** [isokissa3/WorldGuardExtraFlagsPlugin#21]
This is quite urgent. I am running Latest Spigot 1.9.4 build, WorldGuard 6.2, and latest WorldGuard Extra Flags. Here are the versions.
![wg-help](https://user-images.githubusercontent.com/16813676/33523239-88416d38-d7b6-11e7-96d6-7df996ffdaf0.PNG)

The issue I am having is that only some of the flags are working, even though my WorldGuard release is 6.1.3 which is valid under the requirement posted on the plugin's spigot page. It should work. My WorldEdit is also at the latest version. I need someone to help with this!

Here are the flags that work, and don't work.
**RED** = NOT WORKING
**GREEN** = WORKING
**YELLOW** = I did not test that flag.
![wg flags help](https://user-images.githubusercontent.com/16813676/33523271-1dca3452-d7b7-11e7-898b-b36acca5cdd3.PNG)

Everything should be compatible. I don't understand where the problem lies. Again, I need this for 1.9.4. I tested on 1.10.2, and the result was the same. However it does work on 1.12.2. Keep in mind, I have tried numerous builds from various supported versions of WorldGuard from http://builds.enginehub.org/job/worldguard?branch=master&page=1. I've been at it for well over 24 hours. Help is highly appreciated.

_**LINKS:**_
I am using:
WorldGuard: https://dev.bukkit.org/projects/worldguard/files/956770/download
WorldGuard Extra Flags: https://www.spigotmc.org/resources/worldguard-extra-flags.4823/
Server version: **1.9.4** - Spigot Buildtools: `java -jar BuildTools.jar --rev 1.9.4`

**Comment by celtic762** [comment]
It's been nearly a month. Has there been any movement on this? My server makes heavy use of these flags. Also i can verify the same flag issues with the most recent spigot installed and same pluggin versions.
<p>Cheers

**Comment by Flavourized** [comment]
Ehm, I'm not the dev, but WG6.2 won't work on 1.9.4 even though it says it will.

WG6.1.2 is made for 1.10.x & 1.9.x
WG6.2 is made for 1.11.x
WG6.2.1 is made for 1.12.x


Please remember that I know the files say "up to" and supports all version up to, but that isn't not the case. 

If you use 6.2 or higher on 1.9 or 1.10, this plugin won't work. While you may not have issues with WG on your server, this plugin will have issues with WG and your server version.

Short answer: This plugin will only work if you are in 1 of the following states:

- server is 1.11.2, WG is 6.2, WGextraflags is 2.14.2
- server is 1.12.2, WG is 6.2.1, WGef is 2.14.2

These are the only 2 ways this plugin will work. The 6.1.3 requirement is false and doesn't apply. The plugin will use methods which need that 6.1.3 version, but it's useless if the server version match. 

I know this isn't the answer you want to hear, but I had the same exact issue as you. The 2 setups I mentioned above are the only ways to make this plugin work on your server.

The only other way is to get a plugin similar to this custom developed for your server version

**Comment by isokissa3** [comment]
Having permissions to `worldguard.region.bypass.<world>` will prevent the flags from happening, also make sure you have `use-player-move-event` set to true in WorldGuard config
