### ISSUE TITLE
Teleport entry

### ISSUE THREAD

**Issue by Mayzone** [isokissa3/WorldGuardExtraFlagsPlugin#28]
Hello
Teleport-entry flag doesn't work because region.bypass permission is applied but even if its not in the permissions file, ill need to rejoin server to use the flag from world to world. f.ex im in world and tp to world2, i cant tp back unless i rejoin. Could you make entry and exit flags more compatible with other worlds?

Best regard

**Comment by isokissa3** [comment]
Bypass permission now supports the following: worldguard.region.bypass.<world>.<region>.<flag>
