### ISSUE TITLE
Not working with Spigot 1.12 GA Release

### ISSUE THREAD

**Issue by smmmadden** [isokissa3/WorldGuardExtraFlagsPlugin#3]
Hi - I've received several reports that the latest build of World Guard Extra Flags is not working on 1.12.  It is most likely due to building the Jar when the pre-release builds were out there.  Now since GA, it would need to be updated once more.  Once it is updated and posted on the Spigot page, I'll update the Spigot Compatible Plugins and my spreadsheet showing support for 1.12.
Thanks,
Steve

**Comment by isokissa3** [comment]
Tested it on 1.12 after it came out, had no issues
