### ISSUE TITLE
Custom Flags not working (Factions responsible?)

### ISSUE THREAD

**Issue by ShawnPR1** [isokissa3/WorldGuardExtraFlagsPlugin#32]
The custom flags are not working in the world where I have factions enabled. I de-opped myself and changed my group to the default group to test this (I have no personal permissions either) yet it still did not work (I'm mainly stating this to clarify I do not have permission to bypass the flags).

I went to a part of land that was Wilderness, defined a new region then added the `give-effects speed 1` flag to the region. It still did not work.

The custom flags do work in every other world. Could it be Factions causing this issue?

**Comment by ShawnPR1** [comment]
I actually just want to add: I just realized none of the flags work. Not even the default ones like invincible.

It was not like this before installing the custom flags. Will unload the custom flags plugin to verify that it is indeed the cause of these errors.

**Comment by ShawnPR1** [comment]
Sorry for multiple comments this will be the last:

After unloading the plugin the flags are working again (default WorldGuard flags).

It seems that this plugin causes all the flags to not work in a Factions-enabled world.

**Comment by isokissa3** [comment]
Related to 112fc75 and to 63c2c35
