### ISSUE TITLE
command-on-entry

### ISSUE THREAD

**Issue by TheTitanFox** [isokissa3/WorldGuardExtraFlagsPlugin#38]
Hey, after assigning a command to be ran via the flag command-on-entry it prints a chat message "you don't have permission". I was under the assumption that the flag runs as if the player was an OP? Therefore they would have permission correct?

It's to run the /sethome when a player enters the region in a way to set up a respawn type system at different locations depending which the player visited last.

**Comment by axemwa** [comment]
try console-command-on-entry

**Comment by TheTitanFox** [comment]
I've tried that but the console can't run the /sethome command it can only be set with players who have permission to set it (that would be easily solved if I gave players permission for the command but I don't want them to be able to physically use the command, I only want the command to be ran on their behalf)

**Comment by axemwa** [comment]
I think I know what you mean I wanted something similar with towny where i didn't want default players to have access to the /town spawn command but I wanted them to access the same command from the menu so that they had to either pay to teleport or wait until theres a war which activates free town spawning. so what I did was I created a permissions group called townytel that gives players the towny.* permission which overrides all commands allowing them to use the /town spawn command but the way I had it set up was so that players would only get that permission for 1 or 2 seconds when they pressed the town spawn button so that the command could be done by the player since console cant do the command /town spawn (player) if that all makes sense.

Here's what I did anyway using deluxe menus

        left_click_commands:
       *- '[console] lp user %player_name% parent addtemp townytel 1s'* <--Temp permission + time given
        - '[console] eco take %player_name% 50'    ^Mind you I had to have towny.* set in that group
        - '[close]'
        - '[player] town spawn'
        - '[sound] ENTITY_ENDERMEN_TELEPORT'
I'm thinking oyu might be able to do something similar with the flags hope that all made sense and good luck

**Comment by TheTitanFox** [comment]
Thanks @axemwa I appreciate the help and advice :) You've made me think about it from a different approach. What I could do is have the console-command-on-entry assign the player either with the permission to run the /sethome command or assign them to a temporary group that has the permissions for it and have that only be applicable for a timed period so that say after two seconds they lose the permissions thus are not able to physically run the command themselves.

With the permissions then assigned to them I could then run another command-on-entry line to /sethome which should then in theory work because the player DOES indeed have permission for the command (it just expires after a few seconds to they can't go around setting their own home teleports) 

I'll try this way of doing it and get back to you with any news.

Thanks again for your input and fingers crossed this works :)

**Comment by axemwa** [comment]
No problem hope it works out for you, just making sure all the timings are right.

**Comment by TheTitanFox** [comment]
Ok so I've done what I said I would above and I have a feeling it will work.... However that being said it appears to run the /sethome command before the timed permission is granted. Is there any option to add a delay between flags? That way I could delay it running the /sethome command until after it's granted the permission, right now it's trying to do one before the other in the wrong order!

**Comment by axemwa** [comment]
I had that issue aswell have you tried in the order in the example I set above?

**Comment by axemwa** [comment]
oh i use menu commands which you can add delays to, I don't think you can set delays in worldguardextraflags

**Comment by TheTitanFox** [comment]
Yeah I use a similar menu system. The whole premise I was striving to achieve would be that upon discovering a specific location the player would be granted permission to use a menu to teleport back to locations they've discovered. What I was trying to get WorldGuardExtraFlags to do was to force the player to run the /sethome command when they enter one of these locations so that if the player dies they will respawn at the last discovered location. If that makes any sense that's what I was striving to achieve. I was hoping that WGEF would be able to handle this easily, you're absolutely right I could do this through menus the only problem there is that if a player doesn't directly teleport, say he/she just discovers a new location but doesn't actually teleport to it and then they die, they won't respawn at that location they will respawn to wherever they last teleported to.

A work around that could work is have two worldguard regions. One that extends a block or two wider than the other, this initial worldguard region would enable permissions for set home, then upon entering the next region it will perform the command. This should by nature add the delay correctly, it's no ideal but if it works it will be currently the only way I've found that does work lol!

Thanks again :) I'll keep you posted with my progress

**Comment by axemwa** [comment]
I'm sure you will get it to work sounds like a good idea, almost anythings possible in minecraft so you will work out something I'm sure. Glad I can help :P

**Comment by TheTitanFox** [comment]
UPDATE:

So I've done as mentioned above and it now works as I want :) it's not exactly ideal and it's messy in terms of a professional finish, but it is working as I want.

Slightly off topic, I'm only going about it this way until I've set aside some time to develop a plugin that will handle all this by itself.

**Comment by axemwa** [comment]
glad to hear it well done!
