### ISSUE TITLE
Adding flag for fishing

### ISSUE THREAD

**Issue by Flavourized** [isokissa3/WorldGuardExtraFlagsPlugin#39]
Sugegstion would add a flag to deny the fishing event in a region. There is no working plugin/flag/addon for worldguard other than WG blacklist.

**Comment by isokissa3** [comment]
Too specific and would not server purpose for most users

**Comment by Flavourized** [comment]
I disagree. 

In most servers the fishing event allows a player to move AFK or other idle players. Being moved involuntarily through portals, PvP areas, etc is not something I would consider "too specific", as that would apply to most servers..
