### ISSUE TITLE
Respawn-location flag doensn't work 

### ISSUE THREAD

**Issue by TheoRetisch1** [isokissa3/WorldGuardExtraFlagsPlugin#56]
Hej,
The flag respawn-location doesn't work anymore. For instances, I set the flag to a region as follows: /rg flag test respawn-location here. Now, if a normal player without any bypass dies in the region, he will not spawn at the defined location, but at his "normal" spawnpoint. The problem is relatively new and only occurs since the 1.13 updates, earlier it worked. I tested it with version 1.12.2 as well as with version 1.13.2, it didn't work with any version. The plugin loads correctly, other flags work fine and there is no error in the console. I appreciate any help you can provide :). Keep up your great work!

_1.12.2 setup_
Paper 1.12.2 #1582
WorldGuardExtraFlags 3.0.4
Worldguard 6.2.2-SNAPSHOT;1710-95b88ea

_1.13.2 setup_
Paper 1.13.2 #427
Worldguardextraflags 3.0.4
Worldguard (FAWE version): 7.0.0-SNAPSHOT;0dc5781 (https://empcraft.com/fawe/download/)

**Comment by isokissa3** [comment]
Do you have any other plugins beside those?

If you have Discord you can easily contact me there: https://discordapp.com/invite/hbgCMne

**Comment by TheoRetisch1** [comment]
I fixed this problem changing the essentials config option `respawn-listener-priority` to lowest or low.
In CMI you can set `ReSpawn: Enabled: False`.
I was able to solve the problem thanks to the friendly help in the Discord.
