### ISSUE TITLE
Performance issue with 2.14

### ISSUE THREAD

**Issue by Phoenix616** [isokissa3/WorldGuardExtraFlagsPlugin#6]
The new changes to the flags that react on player movements seem to have extreme impact on the server performance. After downgrading to 2.12.2 this doesn't seem to be an issue anymore.

Here are some timings to compare it:

With 2.14: https://timings.aikar.co/?id=97de728cae1f430c8fa0b5c173cac64a
With 2.12.2: https://timings.aikar.co/?id=9ce34e24f7fd4215afdbcac9c3ca1673

As you can see `WorldGuard::Event: c.s.w.b.l.PlayerMoveListener (PlayerMoveEvent)` is using way more ticks in the first one with 2.14 than with the second one with 2.12.2. Nothing else about the server setup changed between these timings.

**Comment by EvilOlaf** [comment]
Confirmed with 2.14
no issue with 2.12.1
Using Spigot 1.8.8

**Comment by isokissa3** [comment]
Looks like I have made mistake and I'm opping and deopping people even if it's not needed causing permisisons to recalculacate and use fair more resources then it shoud

**Comment by EvilOlaf** [comment]
Would be awesome if this gets fixed. Having the ability to execute commands on region entry/exit could be REALLY useful.
Thanks for that.

**Comment by isokissa3** [comment]
Fixed

**Comment by EvilOlaf** [comment]
Not really. Still heavy impact.

With 2.14.1 (short sample):
```
Total: 70.844s (Ticks: 747) - Sample Time: 66.257s  - Spigot Version: 21fe707-e1ebe52 (MC: 1.8.8)
Average Entities: 1,493.43 / 3,297.32 (45.29%) - Average Players: 36.05 - Average TPS: 11.27 - Server Load:  177.00%

WorldGuard v6.1.3-SNAPSHOT;c904242Total: 39.923 s Pct: 60.25%
      57.79%	 102.44%	 38.29 s	    51.22 ms	  28	      21.0k	    PlayerMoveListener::onPlayerMove(PlayerMoveEvent)
```

With 2.14.1 (long sample):
```
Total: 896.809s (Ticks: 17994) - Sample Time: 914.114s  - Spigot Version: 21fe707-e1ebe52 (MC: 1.8.8)
Average Entities: 1,132.53 / 2,608.57 (43.42%) - Average Players: 32.40 - Average TPS: 19.68 - Server Load:   85.31%

WorldGuard v6.1.3-SNAPSHOT;c904242Total: 331.81 s Pct: 36.30%
      32.71%	  33.27%	299.00 s	    16.63 ms	  10	     181.5k	    PlayerMoveListener::onPlayerMove(PlayerMoveEvent)
```


With 2.12.1
```
Total: 1016.354s (Ticks: 29816) - Sample Time: 1521.014s  - Spigot Version: 21fe707-e1ebe52 (MC: 1.8.8)
Average Entities: 1,855.70 / 3,822.00 (48.55%) - Average Players: 39.20 - Average TPS: 19.60 - Server Load:   52.00%

WorldGuard v6.1.3-SNAPSHOT;c904242Total: 52.334 s Pct: 3.44%
      0.19%	   0.20%	  2.95 s	     0.10 ms	  15	     450.8k	    PlayerMoveListener::onPlayerMove(PlayerMoveEvent)
```

**Comment by isokissa3** [comment]
Not sure if the issue is with oping & deopping but removed it altogether to see if it fixes the issue. Not gonna put it yet to spigot so I don't spam everyone who is following with useless updates.

Precompiled: http://download.goldtreeservers.net/WorldGuardExtraFlagsPlugin.jar

**Comment by EvilOlaf** [comment]
Aight, I'll give it a try and catch up the next day or two.

**Comment by EvilOlaf** [comment]
Looks good so far.
```
Total: 2145.999s (Ticks: 99086) - Sample Time: 4963.624s  - Spigot Version: 21fe707-e1ebe52 (MC: 1.8.8)
Average Entities: 1,581.17 / 3,025.30 (52.26%) - Average Players: 22.38 - Average TPS: 19.96 - Server Load:   34.51%
WorldGuard v6.1.3-SNAPSHOT;c904242Total: 75.002 s Pct: 1.51%
       0.13%	   0.13%	  6.64 s	     0.07 ms	 8.5	     839.7k	    PlayerMoveListener::onPlayerMove(PlayerMoveEvent)
```
I'll do another sample with more average players.

**Comment by isokissa3** [comment]
Good, I'm gonna keep it like that because we have the console-command-on-entry & exit flag anyway. If someone actually needs to run the commands as op then I might look back at this again. I don't understand how it was working just fine with the old version... It even ops & deops players more. Might have something to do how your regions are done or its weird bug with WG. If it still keeps happening lemme know, Going to close for now.
