### ISSUE TITLE
New feature: on-entry-delay & on-exit-delay flags

### ISSUE THREAD

**Issue by JohOply** [isokissa3/WorldGuardExtraFlagsPlugin#62]
Hi,

Would you add a new delay flag for on-entry and on-exit (console, command and teleport maybe)
It could be useful to delay commands if player move between regions quickly

Delay flag could also be added to delay greeting and farewell WG messages

Thanks for reading.

**Comment by isokissa3** [comment]
Delayed commands should be handled by other plugins as for example Skript, creates too much complexity for this plugin in my opinion
