### ISSUE TITLE
Have an issue with not finding worldguard on latest version.

### ISSUE THREAD

**Issue by Antmanofgod** [isokissa3/WorldGuardExtraFlagsPlugin#63]
Running Paper-1.13.2-b455, using worldguard-legacy-7.0.0-SNAPSHOT-dist, from FAWE Website, and using FastAsyncWorldEdit-bukkit-18.11.21-99fb2b5-2072, and it's giving me this error:

22.11 20:42:25 [Server] INFO Missing either WorldGuard or WorldEdit, Disabling Custom Flag Features...
22.11 20:42:25 [Server] INFO Latest WorldGuard/WorldEdit features could be missing. Please Update!
22.11 20:42:41 [Server] WARN Could not determine original WorldEdit version, treating it as 6.X!

UPDATE: Now getting this...
ERROR Could not pass event ChunkUnloadEvent to WorldGuardExtraFlags v4.1.1

**Comment by isokissa3** [comment]
You need to use WG 7 Beta 2 for 4.1.1
