### ISSUE TITLE
WorldGuardExtraFlags breaks AsyncWorldEdit

### ISSUE THREAD

**Issue by Bobcat00** [isokissa3/WorldGuardExtraFlagsPlugin#64]
Exception when doing //replace command. See: https://pastebin.com/BLcgJCX6

I'm using CraftBukkit 1.12.2 with:

- AsyncWorldEdit 3.5.4
- WorldEdit 6.1.9,caf0ad9 which is the released version for 1.12.2 from https://dev.bukkit.org/projects/worldedit/files
- WorldGuard 6.2.2-SNAPSHOT,8eeab68 which is the released version for 1.12.2 from https://dev.bukkit.org/projects/worldguard/files
- WorldGuardExtraFlags 4.1.1

**Comment by isokissa3** [comment]
Fixed in 56e6dc8

**Comment by Bobcat00** [comment]
Looks good.  Thank you.
