### ISSUE TITLE
Suggestion - afk timer (kick, on command)

### ISSUE THREAD

**Issue by TNTUP** [isokissa3/WorldGuardExtraFlagsPlugin#65]
A suggestion, a flag which allows server admins in regions, afk-timer-kick, afk-timer-command. 

With afk-timer-kick, if the server admin sets the flag in minutes, eg: 15 minutes the player will get kicked for being afk in that region (useful for public spawners)

Same as the afk-timer-kick but instead of kick it will do a command instead. eg 15 minutes spawn. It will send the player at the spawn or whichever command the admin chooses.

Commands like, /rg flag regionname afk-timer-kick 15 and /rg flag regionname afk-timer-command 15,spawn

I don't know if typing like "afk-timer-command 15 command" would work as it would treat as invalid?

**Comment by isokissa3** [comment]
Out of plugins scope
