### ISSUE TITLE
Play-sounds flag working like 1.8, but server is 1.11.2

### ISSUE THREAD

**Issue by Nariko13** [isokissa3/WorldGuardExtraFlagsPlugin#7]
well it's just a copy/pasta from the discussion ^^" :

It seems that the Play-sounds flag work like 1.8 but i want it to work like 1.9, i have 111.2 spigot server,

Can someone help me (i am using Disc for a music in a region, but people will have the music still playing when the get out the region and i want it to stop and begin on enter/exit. Also if they re-enter, the music will play again while the first one is still playing, so it gives weird result

& I don't want to install regionevent plugin because it brokes the enderpearl flag ! :/

Sorry for my bad english.

**Comment by isokissa3** [comment]
This was fixed in 7648a0f and was missed for long time
