### ISSUE TITLE
Keep-inventory, keep-exp Bug?

### ISSUE THREAD

**Issue by jovosa** [isokissa3/WorldGuardExtraFlagsPlugin#77]
I did a zone with a pvp i did /rg flag region keep-inventory yes, /rg flag region keep-exp yes
and when i kill someone there its dupelicated the items hes items are keeped but im still getting hes armor.

**Comment by jovosa** [comment]
can you help me please?

**Comment by s1h4d0w** [comment]
Use `true` instead of yes.
