### ISSUE TITLE
Give-effects flag deletes effects with the same attribute

### ISSUE THREAD

**Issue by TheoRetisch1** [isokissa3/WorldGuardExtraFlagsPlugin#79]
When leaving regions with the give-effects flag, effects with the same attribute are deleted.

An example:
1) Create a region with jump boost: /rg flag region-name give-effects JUMP 1
2) Give yourself the jump effect: /effect give player minecraft:jump_boost 300 3
And another effect of your choice: /effect give Fangorn minecraft:haste 300 3
3) Leave the region.
4) Notice that the jump effect has been removed, but the other effect remains. 

The example works for other effects too.

Paper 1.13.2 - 627
WorldGuard: 7.0.0-SNAPSHOT;1820-ea47e93
WorldGuardExtraFlags: 4.1.2

**Comment by TheoRetisch1** [comment]
Any news on this?

**Comment by TheoRetisch1** [comment]
I'm still having trouble with this mistake. Do I need more information about the solution?

**Comment by TheoRetisch1** [comment]
It would be awesome if you could resolve this issue :)

**Comment by isokissa3** [comment]
This was most likely fixed in be12951
