### ISSUE TITLE
Inventory Duplication on Death with keepinventory flag

### ISSUE THREAD

**Issue by Xardas88** [isokissa3/WorldGuardExtraFlagsPlugin#83]
### Description
With the flag keep-inventory set true in all region, incluse __global__ region, Players on death both keep and drop their inventories, duplicating everythings.
### Steps to Reproduce
Set flag keep-inventory to true
die and keep and drop all inventory
### Expected Behavior
Keep my inventory and not drop it
### Server Information
* **Server version/platform:**         Paper version git-Paper-152 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
* **WorldEdit Version:**  7.0.1-rc1;edb2e91
* **WorldGuard Version:**        7.0.1-SNAPSHOT;1946-f37acd3
* **WorldGuardExtraFlags Version:**   4.1.2
### Additional Info
There is a change to spigot keepinventory method/event
 https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-14-4-development-builds.369724/page-81#post-3491206

**Comment by isokissa3** [comment]
My plugin has always done this, you most likely have issue with some other plugin.

**Comment by Bobcat00** [comment]
Here's the fix EssentialsX did - https://github.com/EssentialsX/Essentials/commit/d98f8b3467e8684a7754f99237417d5fabb9d712
Maybe you have to do the same thing?
