### ISSUE TITLE
night vision effect not working?

### ISSUE THREAD

**Issue by Ensect** [isokissa3/WorldGuardExtraFlagsPlugin#89]
this should work right? it says it's good but the effect doesnt activate... 

im using worldguard 6.2 with latest version and on mc 1.8.9

`/rg flag warzone give-effects night_vision 1`

**Comment by isokissa3** [comment]
**Flag is not working:**
Make sure you do not have permissions for:

worldguard.region.bypass.<world>.<region>.<flag>

Also make sure you have use-player-move-event set to true in WorldGuard config.

Please also note that if you are OP you have the permissions to bypass any flag.
