### ISSUE TITLE
command-on-entry and command-on-exit wrong behavior

### ISSUE THREAD

**Issue by EvilOlaf** [isokissa3/WorldGuardExtraFlagsPlugin#9]
Hey there,

while playing around with the new flags I discovered that `command-on-exit` acting the same way as `command-on-entry`. To say both flags executing their commands on entry, not on exit.

As always thanks for reading.

WGEF 2.14.1
Spigot 1.8.8

**Comment by isokissa3** [comment]
Thanks! Had small mistake. Fixed

**Comment by EvilOlaf** [comment]
Well done.
Thank you once again!
