### ISSUE TITLE
how do you do console-command-on-entry for specific people?

### ISSUE THREAD

**Issue by Ensect** [isokissa3/WorldGuardExtraFlagsPlugin#90]
i'm trying to set up a parkour and at the end it gives you the permission to get a special kit prize however i'm having trouble identifying how to give the player in question the permission from the flag

i tried : 

/rg flag parkourwin console-command-on-entry pex user %player% add essentials.kits.parkourvictory

and 

/rg flag parkourwin console-command-on-entry pex user {player} add essentials.kits.parkourvictory

sorry if there's some stupidly obvious answer :)

**Comment by isokissa3** [comment]
The actual placeholder is %username%
