### ISSUE TITLE
Worldedit with members/owners of region

### ISSUE THREAD

**Issue by Mikebbe** [isokissa3/WorldGuardExtraFlagsPlugin#98]
Currently the worldedit flags only allows or denys worldedit inside the region

I dont know if it is a bug or a feature that havent been added, but as it is right now, everyone can use worldedit in a plot when it is allowed, instead of just owners/members being able to use it.

Running Paper 1.15.1

**Comment by isokissa3** [comment]
You should use the -g option to specify the group you which to apply the flag to.

**Comment by Mikebbe** [comment]
I mean owner/members of the specific region, not general ranks on the server.

basicly to make a plot system, where people cant build or worldedit in the general area, but in their own plot they can use both worldedit and build normally, but other players cant

**Comment by isokissa3** [comment]
Please refer to WorldGuard documentation

https://worldguard.enginehub.org/en/latest/regions/flags/#region-groups
